### ISSUE TITLE
Got ===FILE_CONTENTS_START=== every file opened with AceIDE

### ISSUE THREAD

**Issue by kemalelmizan** [AceIDE/editor#10]
Issue happened after update to 2.5.4

**Comment by kemalelmizan** [comment]
I believe [this](https://github.com/AceIDE/editor/blob/4ef058f5ecd52b091fc266f51c48f9be2731a038/src/Modules/FileOps.php#L52) is the culprit.

```
		echo '===FILE_CONTENTS_START===';
		echo $wp_filesystem->get_contents($file_name);
		die(); // this is required to return a proper result
	}
```

why do you echo that?

**Comment by shanept** [comment]
Hi kemalelmizan,

Please see this commit: 6d4d6e123c15a71ae81b7a44e52e66a9340f8913

Your browser is simply caching the load-editor javascript file, so as soon as you clear the cache, you will see the editor return to normal.

It seems a lot of themes and plugins output stuff where they shouldn't. Sometimes whitespace, sometimes PHP notices/warnings. These usually make their way into the file whilst downloading. This feature ensures all that noise may be trimmed off.

Kind Regards

**Comment by kemalelmizan** [comment]
oh yeah that's maybe the problem
thanks
