### ISSUE TITLE
Search and Replace Issue

### ISSUE THREAD

**Issue by X-Raym** [AceIDE/editor#11]
Hi !

When you make Search and Replace, once you click on the replace field (to enter what you need), it automatically replace the first occurence of the search results by what was in the replace field, without even clicking on the replace button.

![Demo](http://i.imgur.com/3KZlzMF.gif)

This is not very convenient as it doesn't let the user write his request properly.

**Comment by shanept** [comment]
Hi X-Raym,

Thanks for this. I have pushed an update. It will be on the WP repo soon.
