### ISSUE TITLE
AceIDE needs an icon for the WP icon library.

### ISSUE THREAD

**Issue by rdytogokev** [AceIDE/editor#12]
I made an icon that I hope you like and hope that you'll include in your next update.

![icon-128x128](https://cloud.githubusercontent.com/assets/2678654/24022888/5d35cd32-0a7f-11e7-9e60-c7098e1423d4.png)
![icon-256x256](https://cloud.githubusercontent.com/assets/2678654/24022887/5d351a54-0a7f-11e7-8fec-31348221362f.png)

**Comment by shanept** [comment]
Hi rdytogokev,

That looks pretty cool! Did you have any thoughts as to where to put it on the IDE?

Thanks

**Comment by rdytogokev** [comment]
![wp-directory](https://cloud.githubusercontent.com/assets/2678654/24026574/5f2faff4-0a98-11e7-97c5-ec35413628e9.png)
I am really glad that you like it. I was thinking that initially it should show up in the official Wordpress Plugin directory when people are searching for AceIDE.

Here is the WordPress documentation on how to make the icon show up in the official plugin directory.
[https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#plugin-icons](https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#plugin-icons)

Since you like it, I will try to work up some alternative versions of the design for the IDE interface.

**Comment by shanept** [comment]
That's great! I love it!

I was thinking that if there were a version with the two colours swapped, say the words were that redish colour and the background white with the background grey - that would fit in very nicely above the file browser. If all the cropped background codey bits were removed, it would create a rather interesting effect, I think.

**Comment by rdytogokev** [comment]
I will get working on it.

**Comment by shanept** [comment]
Awesome! Thank you so much for this

**Comment by rdytogokev** [comment]
After playing around with several variations. I came up with this. What do you think?
![idea-1 fw](https://cloud.githubusercontent.com/assets/2678654/24027310/e71f2ac6-0a9c-11e7-95aa-a25bd7f2ec2d.png)

If you like it, here is the logo by itself with a transparent background (retina ready). So if you use it make sure to set the width and height to half the actual width and height. 
This is the code -> `<img src="logo.png" width="111" height="60">`
![logo](https://cloud.githubusercontent.com/assets/2678654/24027510/6c6e954e-0a9e-11e7-95de-2a6b6bc0f7ec.png)

**Comment by shanept** [comment]
Simple, but clean. Very nice!
I have a few other things in the github queue for a new version ready to be pushed. I'll add this, and it should appear in the repo rather soon.

By the way, the original image is now live on WordPress's plugin repo, thanks for your work!

**Comment by rdytogokev** [comment]
No prob. 
If you want to add me to the contributor list in the README.md file that would be cool.
My name is Kevin Young - [RdyToGo Web Design](https://rdytogo.com)

I may have some other little suggestions, just graphical UI stuff. If you would like I can prepare some artwork of the ideas for later inclusion. Most of it will just make things look more modern and crisp. How does that sound?

**Comment by shanept** [comment]
Yeah for sure, I'll add you to the contributor list.
And I'm more than happy to hear your suggestions. Front end isn't my strong point, so feel free to fire away, but if you could open another issue for those it would be great.

**Comment by rdytogokev** [comment]
sure thing!

**Comment by shanept** [comment]
Kevin,

What is your wordpress handle? If you can provide that, I will be able to add you on WordPress as a contributor as well.

Thanks

**Comment by rdytogokev** [comment]
Shane, my WordPress handle is rdytogollc.  Thanks

**Comment by shanept** [comment]
Thanks Kevin. You're now a contributor! I'll push the new version to wp.org soon.
