### ISSUE TITLE
Feature Request: .SCSS File Syntax Highlighting

### ISSUE THREAD

**Issue by lukefiji** [AceIDE/editor#17]
This one shouldn't be too hard as it's already built into ACE Editor - I'm wondering if you could get .SCSS file syntax highlighting enabled? Mainly, to use with the [WP-SCSS Plugin](https://wordpress.org/plugins/wp-scss/)

**Comment by lukefiji** [comment]
Well, I went ahead and did it - I created a [pull request](https://github.com/AceIDE/editor/pull/18) so you should be able to check out what I did.

**Comment by shanept** [comment]
I'm sorry, I only just saw this!
Thanks for the PR, I'll check it out.
