### ISSUE TITLE
Feature Request: Apply IDE to page/post editors

### ISSUE THREAD

**Issue by kyle-charlton** [AceIDE/editor#19]
Would it be possible to use the IDE functionality (syntax highlighting, tabbing, etc...) in the post and page editors? It would be great if there was an option to enable the IDE (minus the file explorer of course) in the page and post editor. Currently I use the [HTML Editor Syntax Highlighter](https://wordpress.org/plugins/html-editor-syntax-highlighter/) plugin to accomplish this, but it would be awesome if AceIDE could do this as I'm a huge fan of this project and it would mean 1 more plugin that I can remove from my installs.

**Comment by shanept** [comment]
I like the sound of that :)

**Comment by shanept** [comment]
Hi kyle-charlton,

As of WordPress 4.9, core is making efforts to build this into WP itself. In addition, there are a multitude of other plugins, such as the one you mentioned, that already achieve this.

Furthermore, I see aceide as more of a development plugin, whereas this feature I believe is something that would be more of a production feature. For these reasons, I don't think there is much point implementing this in AceIDE.

I do appreciate the idea, and the support. I hope you find AceIDE useful!

Kind Regards
