### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by malcalevak** [AceIDE/editor#20]
I went to see how this project was licensed, but I didn't find one. I'd suggest adding one!

**Comment by shanept** [comment]
I appreciate the tip! But I love open source software and have no desire to license this :)

**Comment by malcalevak** [comment]
Sorry, I think I might not have been entirely clear. I meant explicitly including a GPL, GNU, or MIT license, to indicate that it's still open source, free to use, and free to modify. Including this license removes ambiguity about the terms of usage.
