### ISSUE TITLE
BUG: AceIDE doesn't seem to work on some websites.

### ISSUE THREAD

**Issue by EliW** [AceIDE/editor#24]
I run a number of sites.  Many of them are running AceIDE just fine.   However one in particular, well, doesn't.  It's a multisite and whenever I enable AceIDE on it, well, it 'borks' :)  WPIDE runs fine on it however, except of course that WPIDE has gotten so old as to start to become un-usable.

I don't see any PHP errors, I do see some Javascript errors in the console.  They are:
![screen shot 2018-01-16 at 8 19 29 pm](https://user-images.githubusercontent.com/1153183/35020534-9c76c2c8-fafa-11e7-9e9e-e4fee9d8564f.png)

From looking at this, looks like the URLs for the javascript are getting messed up somehow.  I went a bit deeper and seemed to find the problem.

There are two lines in the IDE.php file that are incorrect inside of add_admin_js() ... After doing a fair bit of effort to get the proper $plugin_url ... It's then ignored for both the Ajax endpoint, and the jqueru-file-tree lines.

Changing them respectively to the following seems to fix this for me:

line 153:
		wp_enqueue_script( 'jquery-file-tree', "{$plugin_url}src/js/jqueryFileTree.js", array( 'jquery' ), $idever );

line 181:
			'url' => "{$plugin_url}src/Ajax.php"

**Comment by shanept** [comment]
Hi Eli,

That's great stuff. Thanks for that. Would you be able to submit a patch?

⁣Thanks

**Comment by EliW** [comment]
Sure thing ... may not be until next week tho, deep in the midst of getting something live :)

**Comment by shanept** [comment]
That sounds slightly more important! Best of luck, I look forward to the pull request :)

**Comment by EliW** [comment]
Sorry I never got around to submitting a pull request for this.   Went today to go "Right, I finally have all my code working, have some breathing room, what should I do .... Oh yeah, that PR"

Clicks to GitHub, realizes that was 2 weeks ago.  Notices it's already fixed.   Looks around and wonders where 2 weeks went.
