### ISSUE TITLE
BUG: CSS syntax highlighting now working

### ISSUE THREAD

**Issue by kyle-charlton** [AceIDE/editor#26]
I noticed that the syntax highlighting is not working for CSS files.
The php and html syntax highlighting seems to be working, just no the css files. It appears to not recognize the file as css, when you use the keyboard shortcut to create a comment, it adds an html comment rather then the css comment.

**Comment by shanept** [comment]
Hi kyle-charlton,

Thanks for the notice. Am fixing this now.

Kind Regards
