### ISSUE TITLE
Name Disappears 

### ISSUE THREAD

**Issue by Garfie222** [AceIDE/editor#29]
Hi,
I am using the latest wordpress (ver 4.9.2) and your AceIDE plugin (ver 2.6.1). I have to deactivate all of my plug-in's to see AceIDE in the menu on the left side in admin panel. With all of my plug-in's enabled, it is nowhere to be found. It completely disappears.  Can you tell me how I can access AceIDE without clicking on the missing icon?

Thanks,
Garfie222

**Comment by shanept** [comment]
Hi Garfie222,

Sorry for a very delayed response, I am only just seeing this now.
Did you ever resolve this issue?

Thanks

**Comment by shanept** [comment]
Hi Garfie222,

I'm closing this because I haven't heard anything. If you continue to experience this, please feel free to open a new issue.
