### ISSUE TITLE
Not working with WP Job Manager plugins

### ISSUE THREAD

**Issue by Sogofactory** [AceIDE/editor#31]
impossible to use ACEIDE with WP Job Manager installed and active
Files cannot be opened or read anymore

https://wpjobmanager.com/

**Comment by shanept** [comment]
Hi Sogofactory,

I believe this issue is now fixed - can you update the plugin and confirm please?

**Comment by shanept** [comment]
Hi Sogofactory,

As I have not heard anything more about this, I am closing this issue. If you continue to have issues, please feel free to open a new one.
