### ISSUE TITLE
Unable to get file tree information

### ISSUE THREAD

**Issue by spradooooo** [AceIDE/editor#33]
Hello,

Thank you for the wonderful plugin, it really helped me a lot .
I've been using the plugin for some time without any issues but after the latest WP update 4.9.8, I get this error when I access the plugin page "Unable to get file tree information ".

<img src="https://monosnap.com/image/8PpRpn9TFwNQHiTIenSy6x8s1728p0.png">

Is there any conflict with WP or did you test it with latest version?

Hope you can assist me.

Kind regards

**Comment by shanept** [comment]
Hi @spradooooo 

I noticed your comments on issue #30 - would I be correct to assume you have resolved this issue?

**Comment by spradooooo** [comment]
Hi @shanept 

Yes, the issue is resolved for me after I configured ithemes security plugin to enable the editor

and there was another issue also because of smush plugin but after the last update of smush everything working fine

Love the aceIDE editor

![screenshot 2018-11-29 at 1 45 21 am](https://user-images.githubusercontent.com/16766564/49191824-8fdc3a80-f378-11e8-9bcc-4125b63deb4f.png)

**Comment by shanept** [comment]
Hi @spradooooo 

Glad to hear it's all working for you now!

Kind Regards
