### ISSUE TITLE
Error on plugin activation

### ISSUE THREAD

**Issue by imtweetix** [AceIDE/editor#34]
After installing the plugin and attempted to activate I get this fatal error:
**Fatal error: Composer "vendor/" directory missing. in /home/ciwork/public_html/southfloridasinusandallergy.com/wp-content/plugins/editor/AceIDE.php on line 15**

**Comment by shanept** [comment]
Hi Marc,

Sounds like you've uploaded the source straight from GitHub?

You need to install the composer dependencies first. Please see the installation section of the readme file for instructions
