### ISSUE TITLE
FR: Tab / Spaces code Indentation

### ISSUE THREAD

**Issue by X-Raym** [AceIDE/editor#4]
Hi,

Currently, code indentation is made with 4 spaces.

It could be nice to be able to choose between tab or /spaces, and how many spaces number in this case.

Did I miss something ?

Thanks for listening !

**Comment by shanept** [comment]
Hi X-Raym,

There is an option to choose between spaces and tabs. There is not, however, an option to choose how many spaces to use for indentation as of yet.

If you wish to swap between spaces and tabs, you can do so by bringing up the settings dialog and changing the "Use Tabs" option.

Bringing up the settings dialog
![screenshot from 2016-11-23 10-24-33](https://cloud.githubusercontent.com/assets/5936269/20549481/8ef32f5c-b167-11e6-8a1c-3b58b502c92d.png)

Changing the "Use Tabs" option
![screenshot from 2016-11-23 10-24-46](https://cloud.githubusercontent.com/assets/5936269/20549482/94d9492e-b167-11e6-9b37-1526aed54fe9.png)

I'm sure it would be fairly trivial to change the spacing, I shall make this a feature request and get it done.

Kind Regards,
Shane

**Comment by X-Raym** [comment]
@shanept oh, I missed it ! I thought it was tabs like window tabs, not like tab key 🐹 
thanks for taking care of this anyway, having more options for spaces can definitely help some users to not break their indentations !
